"""add_terminal_security_settings

Revision ID: 0620c841335c
Revises: 9ee4fc2c2a44
Create Date: 2026-06-18 12:06:35.464969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0620c841335c'
down_revision: Union[str, Sequence[str], None] = '9ee4fc2c2a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_security_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_security_settings_tenant_id'), 'terminal_security_settings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_terminal_security_settings_user_id'), 'terminal_security_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminal_security_settings_user_id'), table_name='terminal_security_settings')
    op.drop_index(op.f('ix_terminal_security_settings_tenant_id'), table_name='terminal_security_settings')
    op.drop_table('terminal_security_settings')
    # ### end Alembic commands ###

