"""Add asset management models

Revision ID: 09288bb10181
Revises: a200fb1c0c23
Create Date: 2026-06-14 18:29:10.034904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09288bb10181'
down_revision: Union[str, Sequence[str], None] = 'a200fb1c0c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_groups',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'name', name='uq_asset_groups_tenant_user_name')
    )
    op.create_index(op.f('ix_asset_groups_name'), 'asset_groups', ['name'], unique=False)
    op.create_index(op.f('ix_asset_groups_tenant_id'), 'asset_groups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_asset_groups_user_id'), 'asset_groups', ['user_id'], unique=False)
    op.create_table('keychains',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'name', name='uq_keychains_tenant_user_name')
    )
    op.create_index(op.f('ix_keychains_name'), 'keychains', ['name'], unique=False)
    op.create_index(op.f('ix_keychains_tenant_id'), 'keychains', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_keychains_user_id'), 'keychains', ['user_id'], unique=False)
    op.create_table('local_assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keychain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['asset_groups.id'], ),
    sa.ForeignKeyConstraint(['keychain_id'], ['keychains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'name', name='uq_local_assets_tenant_user_name')
    )
    op.create_index(op.f('ix_local_assets_ip'), 'local_assets', ['ip'], unique=False)
    op.create_index(op.f('ix_local_assets_name'), 'local_assets', ['name'], unique=False)
    op.create_index(op.f('ix_local_assets_tenant_id'), 'local_assets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_local_assets_user_id'), 'local_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_assets_user_id'), table_name='local_assets')
    op.drop_index(op.f('ix_local_assets_tenant_id'), table_name='local_assets')
    op.drop_index(op.f('ix_local_assets_name'), table_name='local_assets')
    op.drop_index(op.f('ix_local_assets_ip'), table_name='local_assets')
    op.drop_table('local_assets')
    op.drop_index(op.f('ix_keychains_user_id'), table_name='keychains')
    op.drop_index(op.f('ix_keychains_tenant_id'), table_name='keychains')
    op.drop_index(op.f('ix_keychains_name'), table_name='keychains')
    op.drop_table('keychains')
    op.drop_index(op.f('ix_asset_groups_user_id'), table_name='asset_groups')
    op.drop_index(op.f('ix_asset_groups_tenant_id'), table_name='asset_groups')
    op.drop_index(op.f('ix_asset_groups_name'), table_name='asset_groups')
    op.drop_table('asset_groups')
    # ### end Alembic commands ###
