"""add_incident_ticket_and_owner_fields

Revision ID: 3efa3d189b85
Revises: 0620c841335c
Create Date: 2026-06-25 12:27:53.077694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3efa3d189b85'
down_revision: Union[str, Sequence[str], None] = '0620c841335c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('incidents', sa.Column('ticket_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'ticket_provider')
    op.drop_column('incidents', 'ticket_url')
    op.drop_column('incidents', 'ticket_id')
    # ### end Alembic commands ###
