"""add_notification_config_to_alerting_settings

Revision ID: 9b5ac3b96908
Revises: a5b0975bf204
Create Date: 2026-05-28 14:36:13.655978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5ac3b96908'
down_revision: Union[str, Sequence[str], None] = 'a5b0975bf204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first with a server default so existing rows get an empty object
    op.add_column('alerting_settings', sa.Column('notification_config', sa.JSON(), nullable=True))
    # Backfill existing rows with an empty JSON object
    op.execute("UPDATE alerting_settings SET notification_config = '{}' WHERE notification_config IS NULL")
    # Now make it non-nullable
    op.alter_column('alerting_settings', 'notification_config', nullable=False,
                    server_default=sa.text("'{}'"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerting_settings', 'notification_config')
    # ### end Alembic commands ###
