"""add terminal models

Revision ID: 9ee4fc2c2a44
Revises: 09288bb10181
Create Date: 2026-06-17 10:22:42.540558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ee4fc2c2a44'
down_revision: Union[str, Sequence[str], None] = '09288bb10181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terminal_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('security_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_audit_logs_asset_id'), 'terminal_audit_logs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_terminal_audit_logs_tenant_id'), 'terminal_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_terminal_audit_logs_terminal_session_id'), 'terminal_audit_logs', ['terminal_session_id'], unique=False)
    op.create_index(op.f('ix_terminal_audit_logs_user_id'), 'terminal_audit_logs', ['user_id'], unique=False)
    op.create_table('terminal_chat_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terminal_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('todos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_chat_sessions_tenant_id'), 'terminal_chat_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_terminal_chat_sessions_terminal_session_id'), 'terminal_chat_sessions', ['terminal_session_id'], unique=False)
    op.create_index(op.f('ix_terminal_chat_sessions_user_id'), 'terminal_chat_sessions', ['user_id'], unique=False)
    op.create_table('terminal_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_sessions_asset_id'), 'terminal_sessions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_terminal_sessions_tenant_id'), 'terminal_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_terminal_sessions_user_id'), 'terminal_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminal_sessions_user_id'), table_name='terminal_sessions')
    op.drop_index(op.f('ix_terminal_sessions_tenant_id'), table_name='terminal_sessions')
    op.drop_index(op.f('ix_terminal_sessions_asset_id'), table_name='terminal_sessions')
    op.drop_table('terminal_sessions')
    op.drop_index(op.f('ix_terminal_chat_sessions_user_id'), table_name='terminal_chat_sessions')
    op.drop_index(op.f('ix_terminal_chat_sessions_terminal_session_id'), table_name='terminal_chat_sessions')
    op.drop_index(op.f('ix_terminal_chat_sessions_tenant_id'), table_name='terminal_chat_sessions')
    op.drop_table('terminal_chat_sessions')
    op.drop_index(op.f('ix_terminal_audit_logs_user_id'), table_name='terminal_audit_logs')
    op.drop_index(op.f('ix_terminal_audit_logs_terminal_session_id'), table_name='terminal_audit_logs')
    op.drop_index(op.f('ix_terminal_audit_logs_tenant_id'), table_name='terminal_audit_logs')
    op.drop_index(op.f('ix_terminal_audit_logs_asset_id'), table_name='terminal_audit_logs')
    op.drop_table('terminal_audit_logs')
    # ### end Alembic commands ###
