"""add_subagent_runs_table

Revision ID: a200fb1c0c23
Revises: 3e7f8a9b0c1d
Create Date: 2026-06-08 10:50:58.005536

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a200fb1c0c23'
down_revision: Union[str, Sequence[str], None] = '3e7f8a9b0c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subagent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subagent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subagent_runs_status'), 'subagent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_subagent_runs_subagent_type'), 'subagent_runs', ['subagent_type'], unique=False)
    op.create_index(op.f('ix_subagent_runs_tenant_id'), 'subagent_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subagent_runs_thread_id'), 'subagent_runs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_subagent_runs_user_id'), 'subagent_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subagent_runs_user_id'), table_name='subagent_runs')
    op.drop_index(op.f('ix_subagent_runs_thread_id'), table_name='subagent_runs')
    op.drop_index(op.f('ix_subagent_runs_tenant_id'), table_name='subagent_runs')
    op.drop_index(op.f('ix_subagent_runs_subagent_type'), table_name='subagent_runs')
    op.drop_index(op.f('ix_subagent_runs_status'), table_name='subagent_runs')
    op.drop_table('subagent_runs')
    # ### end Alembic commands ###
