"""add_alerting_tables

Revision ID: bb06333b4752
Revises: e5f6a7b8c9d0
Create Date: 2026-05-27 14:48:55.629722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb06333b4752'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_alert_rules_tenant_name')
    )
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('alert_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_alert_sources_tenant_name')
    )
    op.create_index(op.f('ix_alert_sources_status'), 'alert_sources', ['status'], unique=False)
    op.create_index(op.f('ix_alert_sources_tenant_id'), 'alert_sources', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alert_sources_type'), 'alert_sources', ['type'], unique=False)
    op.create_table('incident_actions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_actions_action_type'), 'incident_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_incident_actions_incident_id'), 'incident_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_actions_tenant_id'), 'incident_actions', ['tenant_id'], unique=False)
    op.create_table('incident_context_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_context_snapshots_incident_id'), 'incident_context_snapshots', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_context_snapshots_tenant_id'), 'incident_context_snapshots', ['tenant_id'], unique=False)
    op.create_table('incident_signal_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'signal_id', name='uq_incident_signal')
    )
    op.create_index(op.f('ix_incident_signal_links_incident_id'), 'incident_signal_links', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_signal_links_signal_id'), 'incident_signal_links', ['signal_id'], unique=False)
    op.create_index(op.f('ix_incident_signal_links_tenant_id'), 'incident_signal_links', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signal_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_impact', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_agent_id'), 'incidents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_incidents_environment'), 'incidents', ['environment'], unique=False)
    op.create_index(op.f('ix_incidents_incident_key'), 'incidents', ['incident_key'], unique=True)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_service'), 'incidents', ['service'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('raw_alerts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ingest_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'payload_hash', 'received_at', name='uq_raw_alerts_tenant_payload_ts')
    )
    op.create_index(op.f('ix_raw_alerts_ingest_status'), 'raw_alerts', ['ingest_status'], unique=False)
    op.create_index(op.f('ix_raw_alerts_payload_hash'), 'raw_alerts', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_raw_alerts_received_at'), 'raw_alerts', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_alerts_source_id'), 'raw_alerts', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_alerts_tenant_id'), 'raw_alerts', ['tenant_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_alert_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('labels_json', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_correlation_key'), 'signals', ['correlation_key'], unique=False)
    op.create_index(op.f('ix_signals_environment'), 'signals', ['environment'], unique=False)
    op.create_index(op.f('ix_signals_fingerprint'), 'signals', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_signals_raw_alert_id'), 'signals', ['raw_alert_id'], unique=False)
    op.create_index(op.f('ix_signals_service'), 'signals', ['service'], unique=False)
    op.create_index(op.f('ix_signals_severity'), 'signals', ['severity'], unique=False)
    op.create_index(op.f('ix_signals_source'), 'signals', ['source'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_tenant_id'), 'signals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_tenant_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_source'), table_name='signals')
    op.drop_index(op.f('ix_signals_severity'), table_name='signals')
    op.drop_index(op.f('ix_signals_service'), table_name='signals')
    op.drop_index(op.f('ix_signals_raw_alert_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_fingerprint'), table_name='signals')
    op.drop_index(op.f('ix_signals_environment'), table_name='signals')
    op.drop_index(op.f('ix_signals_correlation_key'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_raw_alerts_tenant_id'), table_name='raw_alerts')
    op.drop_index(op.f('ix_raw_alerts_source_id'), table_name='raw_alerts')
    op.drop_index(op.f('ix_raw_alerts_received_at'), table_name='raw_alerts')
    op.drop_index(op.f('ix_raw_alerts_payload_hash'), table_name='raw_alerts')
    op.drop_index(op.f('ix_raw_alerts_ingest_status'), table_name='raw_alerts')
    op.drop_table('raw_alerts')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_key'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_environment'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_agent_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_incident_signal_links_tenant_id'), table_name='incident_signal_links')
    op.drop_index(op.f('ix_incident_signal_links_signal_id'), table_name='incident_signal_links')
    op.drop_index(op.f('ix_incident_signal_links_incident_id'), table_name='incident_signal_links')
    op.drop_table('incident_signal_links')
    op.drop_index(op.f('ix_incident_context_snapshots_tenant_id'), table_name='incident_context_snapshots')
    op.drop_index(op.f('ix_incident_context_snapshots_incident_id'), table_name='incident_context_snapshots')
    op.drop_table('incident_context_snapshots')
    op.drop_index(op.f('ix_incident_actions_tenant_id'), table_name='incident_actions')
    op.drop_index(op.f('ix_incident_actions_incident_id'), table_name='incident_actions')
    op.drop_index(op.f('ix_incident_actions_action_type'), table_name='incident_actions')
    op.drop_table('incident_actions')
    op.drop_index(op.f('ix_alert_sources_type'), table_name='alert_sources')
    op.drop_index(op.f('ix_alert_sources_tenant_id'), table_name='alert_sources')
    op.drop_index(op.f('ix_alert_sources_status'), table_name='alert_sources')
    op.drop_table('alert_sources')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
