export interface ProviderTemplate {
  id: string;
  label: string;
  labelEn: string;
  use: string;
  baseUrl: string;
  isOpenAICompatible: boolean;
  defaultSupportsThinking: boolean;
  defaultSupportsVision: boolean;
  defaultSupportsReasoningEffort: boolean;
  defaultSupportsText2Image?: boolean;
  defaultModelType?: string;
  note: string;
  noteEn: string;
}

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  {
    id: "openai",
    label: "OpenAI",
    labelEn: "OpenAI",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: true,
    defaultSupportsText2Image: true,
    note: "",
    noteEn: "Connects to api.openai.com by default, no Base URL needed",
  },
  {
    id: "openai_compatible",
    label: "OpenAI Compatible",
    labelEn: "OpenAI Compatible",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: false,
    defaultSupportsReasoningEffort: false,
    note: "适用于所有兼容 OpenAI API 的厂商，需填写 Base URL",
    noteEn: "For any OpenAI API-compatible provider, requires Base URL",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    labelEn: "Anthropic",
    use: "langchain_anthropic.ChatAnthropic",
    baseUrl: "",
    isOpenAICompatible: false,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "原生 Anthropic provider，支持 extended thinking",
    noteEn: "Native Anthropic provider with extended thinking support",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    labelEn: "DeepSeek",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.deepseek.com/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: false,
    defaultSupportsReasoningEffort: false,
    defaultModelType: "reasoning",
    note: "DeepSeek 开放平台，走 OpenAI-compatible 通道",
    noteEn: "DeepSeek platform via OpenAI-compatible channel",
  },
  {
    id: "azure_openai",
    label: "Azure OpenAI",
    labelEn: "Azure OpenAI",
    use: "langchain_openai.AzureChatOpenAI",
    baseUrl: "",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    defaultModelType: "chat",
    note: "Azure 部署需填写 endpoint 作为 Base URL，并确保 api_version 正确",
    noteEn: "Azure deployment requires endpoint as Base URL and correct api_version",
  },
  {
    id: "gemini",
    label: "Gemini (Google)",
    labelEn: "Gemini (Google)",
    use: "langchain_google_genai.ChatGoogleGenerativeAI",
    baseUrl: "",
    isOpenAICompatible: false,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    defaultSupportsText2Image: true,
    note: "需安装 langchain-google-genai 依赖",
    noteEn: "Requires langchain-google-genai dependency",
  },
  {
    id: "ollama",
    label: "Ollama",
    labelEn: "Ollama",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "http://localhost:11434/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: false,
    defaultSupportsReasoningEffort: false,
    defaultModelType: "chat",
    note: "本地部署，需填写 Base URL 为 http://localhost:11434/v1",
    noteEn: "Local deployment, set Base URL to http://localhost:11434/v1",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    labelEn: "OpenRouter",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://openrouter.ai/api/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "聚合模型平台，统一走 OpenAI-compatible 通道",
    noteEn: "Aggregated model platform via OpenAI-compatible channel",
  },
  {
    id: "groq",
    label: "Groq",
    labelEn: "Groq",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.groq.com/openai/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: false,
    defaultSupportsReasoningEffort: false,
    note: "高速推理平台，走 OpenAI-compatible 通道",
    noteEn: "High-speed inference via OpenAI-compatible channel",
  },
  {
    id: "together",
    label: "Together AI",
    labelEn: "Together AI",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.together.xyz/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "开源模型托管平台，走 OpenAI-compatible 通道",
    noteEn: "Open-source model hosting via OpenAI-compatible channel",
  },
  {
    id: "siliconflow",
    label: "SiliconFlow (硅基流动)",
    labelEn: "SiliconFlow",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.siliconflow.cn/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "国内 AI 模型平台，走 OpenAI-compatible 通道",
    noteEn: "China-based AI platform via OpenAI-compatible channel",
  },
  {
    id: "dashscope",
    label: "DashScope (阿里百炼)",
    labelEn: "DashScope (Alibaba)",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "阿里百炼平台，走兼容 OpenAI 模式",
    noteEn: "Alibaba Bailian via OpenAI-compatible mode",
  },
  {
    id: "zhipu",
    label: "智谱 (GLM)",
    labelEn: "Zhipu (GLM)",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "智谱 AI 平台，走 OpenAI-compatible 通道",
    noteEn: "Zhipu AI platform via OpenAI-compatible channel",
  },
  {
    id: "moonshot",
    label: "Moonshot (月之暗面)",
    labelEn: "Moonshot",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.moonshot.cn/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "Kimi 平台，走 OpenAI-compatible 通道",
    noteEn: "Kimi platform via OpenAI-compatible channel",
  },
  {
    id: "minimax",
    label: "MiniMax",
    labelEn: "MiniMax",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.minimax.io/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "MiniMax 平台，走 OpenAI-compatible 通道",
    noteEn: "MiniMax platform via OpenAI-compatible channel",
  },
  {
    id: "baichuan",
    label: "百川智能",
    labelEn: "Baichuan",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.baichuan-ai.com/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: false,
    defaultSupportsReasoningEffort: false,
    note: "百川 AI 平台，走 OpenAI-compatible 通道",
    noteEn: "Baichuan AI platform via OpenAI-compatible channel",
  },
  {
    id: "lingyiwanwu",
    label: "零一万物",
    labelEn: "01.AI (Yi)",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: false,
    defaultSupportsReasoningEffort: false,
    note: "零一万物平台，走 OpenAI-compatible 通道",
    noteEn: "01.AI platform via OpenAI-compatible channel",
  },
  {
    id: "volcengine",
    label: "火山方舟 (字节)",
    labelEn: "Volcengine Ark",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    isOpenAICompatible: true,
    defaultSupportsThinking: true,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "火山引擎方舟平台，走 OpenAI-compatible 通道",
    noteEn: "Volcengine Ark via OpenAI-compatible channel",
  },
  {
    id: "novita",
    label: "Novita AI",
    labelEn: "Novita AI",
    use: "langchain_openai.ChatOpenAI",
    baseUrl: "https://api.novita.ai/openai",
    isOpenAICompatible: true,
    defaultSupportsThinking: false,
    defaultSupportsVision: true,
    defaultSupportsReasoningEffort: false,
    note: "Novita AI 平台，走 OpenAI-compatible 通道",
    noteEn: "Novita AI platform via OpenAI-compatible channel",
  },
];

export function getProviderById(id: string): ProviderTemplate | undefined {
  return PROVIDER_TEMPLATES.find((p) => p.id === id);
}
